// <auto-generated />
namespace Medica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class PregledStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PregledStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201505201055401_Pregled (Status)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
